import { Platform, StyleSheet } from "react-native";
import {
  HOME_FEED_BG,
  HOME_FEED_CARD_RADIUS,
  HOME_FEED_GOLD,
  HOME_FEED_GOLD_SOFT,
  HOME_FEED_GLASS_BG,
  HOME_FEED_GLASS_BORDER,
  HOME_FEED_GLASS_GOLD_BORDER,
  HOME_FEED_INACTIVE,
  HOME_FEED_MUTED,
  HOME_FEED_THUMB_RADIUS,
} from "./theme";

/** Module-level StyleSheet — no per-render style allocation. */
export const homeFeedPremiumStyles = StyleSheet.create({
  glassCircleButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.035)",
    borderWidth: 1,
    borderColor: "rgba(245,215,120,0.14)",
  },
  headerGlass: {
    backgroundColor: "#241038",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(245,215,120,0.38)",
  },
  /** Solid black header — no glass, thin gold rule. */
  headerSolid: {
    backgroundColor: "#241038",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(245,215,120,0.38)",
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.035)",
    borderWidth: 1,
    borderColor: "rgba(245,215,120,0.14)",
  },
  headerIconButtonActive: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_GOLD_BORDER,
  },
  logoTitle: {
    color: "#F5D76E",
    fontSize: 27,
    fontWeight: "900",
    letterSpacing: 10,
    textShadowColor: "rgba(245,215,120,0.45)",
    textShadowRadius: 10,
  },
  logoSubtitleAccent: {
    color: "rgba(255,255,255,0.92)",
  },

  /** Card shell — light inner glass, no heavy box/shadow. */
  feedCard: {
    marginHorizontal: 5,
    marginBottom: 22,
    borderRadius: 36,
    borderWidth: 1.7,
    borderColor: "rgba(245,215,120,0.62)",
    backgroundColor: "rgba(255,255,255,0.105)",
    shadowColor: "#F5D76E",
    shadowOpacity: 0.46,
    shadowRadius: 34,
    shadowOffset: { width: 0, height: 12 },
    elevation: 22,
    overflow: "visible",
  },
  thumbFrame: {
    margin: 2,
    borderRadius: 34,
    overflow: "hidden",
    backgroundColor: "#050505",
    borderWidth: 1.2,
    borderColor: "rgba(245,215,120,0.24)",
    shadowColor: "#F5D76E",
    shadowOpacity: 0.18,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  metaSection: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 6,
    gap: 3,
    backgroundColor: "rgba(255,255,255,0.032)",
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 13,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#111111",
    borderWidth: 1.4,
    borderColor: "#F5D76E",
    shadowColor: "#F5D76E",
    shadowOpacity: 0.28,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 0 },
    elevation: 6,
  },
  avatarFallback: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "rgba(245,215,120,0.12)",
    borderWidth: 1.6,
    borderColor: "#F5D76E",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#F5D76E",
    shadowOpacity: 0.30,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 0 },
    elevation: 7,
  },
  avatarInitial: {
    color: HOME_FEED_GOLD_SOFT,
    fontSize: 15,
    fontWeight: "700",
  },
  metaTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  churchNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    minWidth: 0,
  },
  churchName: {
    flexShrink: 1,
    color: "#F5D76E",
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "900",
    letterSpacing: 0.45,
    textShadowColor: "rgba(245,215,120,0.35)",
    textShadowRadius: 6,
  },
  videoTitle: {
    color: "#FFFFFF",
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "800",
    letterSpacing: 0.04,
  },
  statsLine: {
    color: "rgba(255,255,255,0.56)",
    fontSize: 13,
    lineHeight: 16,
    fontWeight: "600",
  },
  actionsBar: {
    marginHorizontal: 18,
    marginTop: 0,
    marginBottom: 10,
    borderRadius: 0,
    paddingHorizontal: 4,
    paddingVertical: 4,
    backgroundColor: "transparent",
    borderTopWidth: 1,
    borderTopColor: "rgba(245,215,120,0.22)",
    borderWidth: 0,
    shadowOpacity: 0,
    elevation: 0,
  },
  inlineActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  inlineAction: {
    flex: 1,
    alignItems: "center",
    gap: 1,
    minWidth: 0,
    paddingVertical: 1,
  },
  inlineLabel: {
    color: "rgba(255,255,255,0.50)",
    fontSize: 10,
    fontWeight: "800",
    letterSpacing: 0.08,
    textAlign: "center",
  },
  inlineLabelActive: {
    color: "#F5D76E",
    textShadowColor: "rgba(245,215,120,0.35)",
    textShadowRadius: 6,
  },

  /** TikTok vertical rail — same light inner glass. */
  verticalActionRail: {
    position: "absolute",
    right: 10,
    alignItems: "center",
    zIndex: 20,
  },
  verticalActionGlass: {
    borderRadius: 22,
    paddingVertical: 8,
    paddingHorizontal: 5,
    gap: 12,
    backgroundColor: HOME_FEED_GLASS_BG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_BORDER,
  },
  verticalActionBtn: {
    alignItems: "center",
    gap: 4,
    minWidth: 48,
  },
  verticalIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
  },
  verticalIconWrapActive: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_GOLD_BORDER,
  },
  verticalIconWrapLiked: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: "rgba(255,90,122,0.35)",
  },
  verticalCountLabel: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  verticalTextLabel: {
    color: HOME_FEED_MUTED,
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
  },
  verticalLabelActive: {
    color: HOME_FEED_GOLD_SOFT,
  },
  playBadge: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: "rgba(0,0,0,0.34)",
    borderWidth: 1.6,
    borderColor: "rgba(255,255,255,0.88)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#FFFFFF",
    shadowOpacity: 0.22,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 0 },
    elevation: 10,
  },
  durationBadge: {
    position: "absolute",
    right: 10,
    bottom: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.72)",
    borderWidth: 1,
    borderColor: "rgba(245,215,120,0.38)",
  },

  /** Opaque black tab bar — blocks feed content underneath. */
  tabBarSolid: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: HOME_FEED_BG,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: HOME_FEED_GLASS_GOLD_BORDER,
    height: 70,
    paddingTop: 6,
    paddingBottom: 12,
    ...(Platform.OS === "android" ? { elevation: 0 } : {}),
  },
});
