import { Platform, StyleSheet } from "react-native";
import {
  HOME_FEED_CARD_BORDER,
  HOME_FEED_CARD_RADIUS,
  HOME_FEED_GOLD,
  HOME_FEED_GOLD_GLOW,
  HOME_FEED_GOLD_SOFT,
  HOME_FEED_GLASS_BG,
  HOME_FEED_GLASS_BORDER,
  HOME_FEED_GLASS_GOLD_BORDER,
  HOME_FEED_INACTIVE,
  HOME_FEED_MUTED,
  HOME_FEED_THUMB_RADIUS,
} from "./theme";

/** Module-level StyleSheet — no per-render style allocation. */
export const homeFeedPremiumStyles = StyleSheet.create({
  headerGlass: {
    backgroundColor: HOME_FEED_GLASS_BG,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: HOME_FEED_GLASS_GOLD_BORDER,
  },
  glassCircleButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_GOLD_BORDER,
  },
  glassCircleButtonActive: {
    backgroundColor: "rgba(212,175,101,0.14)",
    borderColor: HOME_FEED_GOLD_GLOW,
  },
  logoGlowShell: {
    flex: 1,
    marginHorizontal: 12,
    minHeight: 48,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(212,175,101,0.07)",
    borderWidth: 1,
    borderColor: HOME_FEED_GOLD_GLOW,
  },
  logoTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "900",
    letterSpacing: 6,
  },
  feedCard: {
    marginHorizontal: 14,
    marginBottom: 22,
    borderRadius: HOME_FEED_CARD_RADIUS,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_CARD_BORDER,
    backgroundColor: "rgba(255,255,255,0.025)",
    overflow: "hidden",
  },
  thumbFrame: {
    borderTopLeftRadius: HOME_FEED_CARD_RADIUS,
    borderTopRightRadius: HOME_FEED_CARD_RADIUS,
    borderBottomLeftRadius: HOME_FEED_THUMB_RADIUS,
    borderBottomRightRadius: HOME_FEED_THUMB_RADIUS,
    overflow: "hidden",
    backgroundColor: "#050508",
  },
  metaSection: {
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 10,
    gap: 6,
  },
  metaRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#12121A",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_GOLD_BORDER,
  },
  avatarFallback: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(212,175,101,0.10)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_GOLD_BORDER,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarInitial: {
    color: HOME_FEED_GOLD_SOFT,
    fontSize: 17,
    fontWeight: "800",
  },
  metaTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 5,
  },
  churchNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    minWidth: 0,
  },
  churchName: {
    flexShrink: 1,
    color: HOME_FEED_GOLD,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
    letterSpacing: 0.35,
  },
  videoTitle: {
    color: "#FFFFFF",
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "600",
    letterSpacing: 0.1,
  },
  statsLine: {
    color: HOME_FEED_INACTIVE,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: "500",
    letterSpacing: 0.2,
  },
  actionsGlassBar: {
    marginHorizontal: 12,
    marginBottom: 12,
    borderRadius: 16,
    paddingHorizontal: 8,
    paddingVertical: 10,
    backgroundColor: HOME_FEED_GLASS_BG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_BORDER,
  },
  inlineActionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  inlineAction: {
    flex: 1,
    alignItems: "center",
    gap: 5,
    minWidth: 0,
  },
  inlineLabel: {
    color: HOME_FEED_INACTIVE,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.25,
    textAlign: "center",
  },
  inlineLabelActive: {
    color: HOME_FEED_GOLD_SOFT,
  },
  verticalActionRail: {
    position: "absolute",
    right: 10,
    alignItems: "center",
    zIndex: 20,
  },
  verticalActionGlass: {
    borderRadius: 28,
    paddingVertical: 10,
    paddingHorizontal: 6,
    gap: 14,
    backgroundColor: HOME_FEED_GLASS_BG,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_BORDER,
  },
  verticalActionBtn: {
    alignItems: "center",
    gap: 5,
    minWidth: 52,
  },
  verticalIconWrap: {
    width: 50,
    height: 50,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(255,255,255,0.05)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_BORDER,
  },
  verticalIconWrapActive: {
    borderColor: HOME_FEED_GOLD_GLOW,
    backgroundColor: "rgba(212,175,101,0.12)",
  },
  verticalIconWrapLiked: {
    borderColor: "rgba(255,90,122,0.45)",
    backgroundColor: "rgba(255,90,122,0.10)",
  },
  verticalCountLabel: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.2,
    textAlign: "center",
  },
  verticalTextLabel: {
    color: HOME_FEED_MUTED,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
  },
  verticalLabelActive: {
    color: HOME_FEED_GOLD_SOFT,
  },
  playBadge: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "rgba(0,0,0,0.52)",
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.85)",
    alignItems: "center",
    justifyContent: "center",
  },
  durationBadge: {
    position: "absolute",
    right: 10,
    bottom: 10,
    paddingHorizontal: 7,
    paddingVertical: 4,
    borderRadius: 8,
    backgroundColor: "rgba(0,0,0,0.72)",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: HOME_FEED_GLASS_GOLD_BORDER,
  },
  tabBarGlass: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(4,4,6,0.94)",
    borderTopColor: HOME_FEED_GLASS_GOLD_BORDER,
    borderTopWidth: StyleSheet.hairlineWidth,
    height: 70,
    paddingTop: 6,
    paddingBottom: 12,
    ...(Platform.OS === "ios"
      ? {
          shadowColor: "#000",
          shadowOpacity: 0.12,
          shadowRadius: 8,
          shadowOffset: { width: 0, height: -4 },
        }
      : { elevation: 4 }),
  },
});
